# Generated by Django 4.0.2 on 2022-05-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('productCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_comment', models.CharField(max_length=30, verbose_name='Автор')),
                ('ia_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить на экран?')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опуюликован')),
                ('comment_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created'],
            },
        ),
    ]
